obstacle_range: 2.5
raytrace_range: 3.0
robot_radius: 0.21
inflation_radius: 0.55

observation_sources: kinect_sensor

kinect_sensor: { sensor_frame: /openni_rgb_frame, data_type: PointCloud, topic: /camera/depth/points, marking: true, clearing: true }
