local_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 4.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 15.0
  height: 15.0
  origin_x: 3.0
  origin_y: 3.0
  resolution: 0.05
