obstacle_range: 2.5
raytrace_range: 3.0

robot_radius: 0.21
inflation_radius: 0.55

observation_sources: scan
#point_cloud_sensor

scan: {data_type: LaserScan, sensor_frame: /laser, topic: /scan, expected_update_rate: 0.4, marking: true, clearing: true}


